
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_0.61.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.61.0_Linux-64bit.deb

script:
  - hugo

deploy:
- provider: pages
  skip_cleanup: true
  github_token: ${{ secrets.GITHUB_TOKEN }}
  local_dir: public
  keep_history: true
  on:
    branch: master
