baseURL = "https://aaltomcc.github.io/cs-ej4101-fall-2019-077-advanced/"
languageCode = "en-us"
theme = "hugo-goa"
title = "My New Hugo Site"
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
dateformat = "Jan 2, 2006"

[menu]

    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
        identifier = "home"
    [[menu.main]]
        name = "Blog"
        url = "/blog/"
        weight = 2
	    identifier = "blog"
