baseURL = "https://aaltomcc.github.io/cs-ej4101-fall-2019-077-advanced/"
languageCode = "en-us"
theme = "hugo-lithium"
title = "My New Hugo Site"
disableKinds = [“taxonomy”, “taxonomyTerm”]

[[menu.main]]
name = "Home"
url = "/"
weight = 1
